### ISSUE TITLE
oc adm must-gather compatibility

### ISSUE THREAD

**Issue by nirs** [nirs/kubectl-gather#3]
Make the output compatible with `oc adm must-gather` to make it easier to work for people using OCP (production) and k8s clusters (testing), and allow using the same tools to analyze and process gathered data from both tools.

We cannot be fully compatible since must-gather structure is less useful (collecting only single cluster, storing everything under very long must-gather version directory), but at lest we can have the similar structure for resources yaml and pod logs.

must-gather may collect more data that this tool may never collect - we don't try to duplicate must-gather. But if we collect the same info we should try to make the output compatible.

## Multiple cluster support

must-gather support single cluster, but you can use --dest-dir to collect multiple cluster into one directory. We support multiple clusters creating directory with all data from all clusters by default.

This should be a problem when using tools, if the tool support single directory we can point the tool to the cluster directory (e.g. gather.timestamp/cluster/).

Output from single run of `kubectl gather -d gather.1 --context perf1,perf2,perf3`

```
$ tree -L 1 gather.1
gather.1
├── perf1
├── perf2
└── perf3
```

Output from 3 runs of `oc adm must-gather --dest-dir must-gather.1`, each with different --context:

```
$ tree -L 1 must-gather.1
must-gather.1
├── perf1
├── perf2
└── perf3
```

## Cluster scope resources

must-gather uses "cluster-scoped-resources", we use "cluster":

Output from ACM must-gather image:

```
$ tree -L 1 must-gather.1/perf1/registry-redhat-io-rhacm2-acm-must-gather-rhel9-sha256-6835423dbaa76467b279bc91d9aad3e9c9022eebe9dd7c7e37f6ead8f2c0ed9f/
must-gather.1/perf1/registry-redhat-io-rhacm2-acm-must-gather-rhel9-sha256-6835423dbaa76467b279bc91d9aad3e9c9022eebe9dd7c7e37f6ead8f2c0ed9f/
├── cluster-scoped-resources
├── event-filter.html
├── gather-acm.log
├── gather-managed.log
├── gather-mce.log
├── gather-proxy.log
├── gather-proxy-mce.log
├── namespaces
├── Ramen_resources
└── timestamp
```

Output from kubectl gather:

```
$ tree -L 1 gather.1/perf1/
gather.1/perf1/
├── cluster
└── namespaces
```

"cluster-scope-resoruces" is not consistent with "namespaces". We will keep the current format unless there is a good reason to change it.

## Group resource by API group

must-gather is using (in most cases):

```
   namespaces/
     namespace/
       group
         resource1
           name1.yaml
         resource2
           name2.yaml
```

This keeps related resource together which is nice when inspecting gathered data.

## Resources with empty group

must-gather sometimes uses "resource":

```
├── pods
│   ├── csi-addons-controller-manager-55cdfc6b8f-75tsw
│   │   ├── csi-addons-controller-manager-55cdfc6b8f-75tsw.yaml
│   │   ├── kube-rbac-proxy
│   │   │   └── kube-rbac-proxy
│   │   │       └── logs
│   │   │           └── current.log
```

And sometimes it creates a fake "core" directory:

```
├── open-cluster-management-agent
...
│   ├── core
│   │   ├── configmaps.yaml
│   │   ├── endpoints.yaml
│   │   ├── events.yaml
│   │   ├── persistentvolumeclaims.yaml
│   │   ├── pods.yaml
│   │   ├── replicationcontrollers.yaml
│   │   ├── secrets.yaml
│   │   └── services.yaml
```

Looks like must-gather does this when keeping multiple resources in single yaml file.

We always keep one resource per file so there is no need to create a "core" directory.

## Multiple resource per file

must-gather sometimes collect multiple resources in single file which makes it very hard to inspect later.

```
├── nsoffer-sub-rbd
│   └── apps.open-cluster-management.io
│       ├── subscriptions
│       │   └── nsoffer-sub-rbd-subscription-1.yaml
│       └── subscriptionstatuses
│           └── nsoffer-sub-rbd-subscription-1.yaml
├── open-cluster-management-agent
│   ├── apps
│   │   ├── daemonsets.yaml
│   │   ├── deployments.yaml
│   │   ├── replicasets.yaml
│   │   └── statefulsets.yaml
```

We always create one resource per file which is easier to use and more consistent.

## Image directory

must-gather group all output under a very very long image directory:

Every image gahter data under its own very long name direcotory. You need know where to look for every resource.

```
$ tree -L 1 must-gather.1/perf2
must-gather.1/perf2
├── event-filter.html
├── quay-io-rhceph-dev-ocs-must-gather-sha256-695ed593e5185c38beb852c584312f6e605831e2eff6e389e7c8e1beccd0c77c
├── registry-redhat-io-rhacm2-acm-must-gather-rhel9-sha256-6835423dbaa76467b279bc91d9aad3e9c9022eebe9dd7c7e37f6ead8f2c0ed9f
└── timestamp
```

This is makes using the gathered data very hard for 2 reasons:
- You have to fight with the very very long directory names when navigating or showing output
- You need to go back and forth to look for gathered data for a single application. For example ACM must-gather collects only ACM resources for an application, and ODF must-gather collects only ODF resources. There is no way to see all the data for a single application in one place.

We try to make a unified view of the cluster in one directory per cluster.

## Pod yaml location

must-gather store pod yaml inside the pod directory:

```
$ tree must-gather.1/perf1/registry-redhat-io-rhacm2-acm-must-gather-rhel9-sha256-6835423dbaa76467b279bc91d9aad3e9c9022eebe9dd7c7e37f6ead8f2c0ed9f/namespaces/openshift-operators/pods
must-gather.1/perf1/registry-redhat-io-rhacm2-acm-must-gather-rhel9-sha256-6835423dbaa76467b279bc91d9aad3e9c9022eebe9dd7c7e37f6ead8f2c0ed9f/namespaces/openshift-operators/pods
├── odfmo-controller-manager-7cb857f855-gdrpg
│   ├── manager
│   │   └── manager
│   │       └── logs
│   │           ├── current.log
│   │           ├── previous.insecure.log
│   │           └── previous.log
│   └── odfmo-controller-manager-7cb857f855-gdrpg.yaml
```

This makes sense, but less consistent with other yamls location.

Changing this requires moving dumping of the yaml to the addon inspecting the resource.

## Pod log location

must-gather keeps pods logs under pod/container/container/logs/:

```
$ tree must-gather.1/perf1/registry-redhat-io-rhacm2-acm-must-gather-rhel9-sha256-6835423dbaa76467b279bc91d9aad3e9c9022eebe9dd7c7e37f6ead8f2c0ed9f/namespaces/openshift-operators/pods/ramen-hub-operator-7f8859756f-5gdvf/
must-gather.1/perf1/registry-redhat-io-rhacm2-acm-must-gather-rhel9-sha256-6835423dbaa76467b279bc91d9aad3e9c9022eebe9dd7c7e37f6ead8f2c0ed9f/namespaces/openshift-operators/pods/ramen-hub-operator-7f8859756f-5gdvf/
├── kube-rbac-proxy
│   └── kube-rbac-proxy
│       └── logs
│           ├── current.log
│           ├── previous.insecure.log
│           └── previous.log
├── manager
│   └── manager
│       └── logs
│           ├── current.log
│           ├── previous.insecure.log
│           └── previous.log
└── ramen-hub-operator-7f8859756f-5gdvf.yaml
```

Using extra level for the container name seems pointless, and we don't anything else but logs, so the logs directory is not needed. The extra directories makes the output harder to use so we will keep the current output unless there is a good reason to change it.

## Previous insecure log

must-gather creates "previous.insecure.log" - not sure why. The file is always empty when using ACM or ODF must-gather images.

Need to check what is this log and if we need it.

## Rook data

Need to check how ODF must-gather image stores ceph logs, host journals, crash reports, and commands output.

## Tasks

- [x] Group resources under group directory (#12)
- [ ] Pods logs directory layout?
- [ ] Check what is the previous insecure log
- [ ] Check Ceph data gathered by ODF must-gather
